---
title: "S&P 500"
author: "Kevin OKiah"
date: "August 15, 2017"
output: word_document
---

* Download the data
```{r cars}
suppressMessages(library(tseries))

NUGTdata <- get.hist.quote('NUGT',quote="Close")
```

Get the dimension of the data and peak at the data structure
```{r}
dim(NUGTdata)
head(NUGTdata)

```


* Calculate log returns
```{r}
NUGTret <- log(lag(NUGTdata)) - log(NUGTdata)
NUGTvol <- sd(NUGTret) * sqrt(250) * 100

#log returns
print(head(NUGTret)) #print head 

print(tail(NUGTret)) #print tail
length(NUGTret)
```

* Calculate volatility measure 
```{r}
## Function for creating volatility Measure
getVol <- function(d, logrets){
          var = 0
        	lam = 0
        	varlist <- c()
          	for (r in logrets) {
            	lam = lam*(1 - 1/d) + 1
            	var = (1 - 1/lam)*var + (1/lam)*r^2
            	varlist <- c(varlist, var)
          	}
          sqrt(varlist)
          }
```


* Calculate volatility over entire length of series for various three different decay factors

```{r}
#Volatility over 10, 30, 100 decay factors
volest <- getVol(10,NUGTret)

volest2 <- getVol(30,NUGTret)

volest3 <- getVol(100,NUGTret)

volatility<-cbind(volest,volest2, volest3)

```

* Plot the results, overlaying the volatility curves on the data, just as was done in the S&P example.
```{r}

plot(volest,type="l", xlab = "Index", ylab = "Volatility", main = "Volatility curves for 3 lookback windows(10, 30, 100)")
lines(volest2,type="l",col="red")
lines(volest3, type = "l", col="blue")
```